// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStepWeb.Data;

#nullable disable

namespace NextStepWeb.Migrations
{
    [DbContext(typeof(NextStepDbContext))]
    [Migration("20260926173703_AddClarificationMetadata")]
    partial class AddClarificationMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextStepWeb.Models.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedTime")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsRecommendedNext")
                        .HasColumnType("bit");

                    b.Property<Guid>("SituationVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Urgency")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("SituationVersionId", "StepOrder")
                        .HasDatabaseName("IX_ActionItems_SituationVersionId_StepOrder");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdversarialWarning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DifferentInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdversarial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAtRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCalmMode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMisuse")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorseAfterAction")
                        .HasColumnType("bit");

                    b.Property<string>("MisuseExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SituationVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportGuidance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnderstandingSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatChanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatHappenedAfterAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatToReassess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorseOutcomeAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SituationVersionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Assessments_SituationVersionId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("SituationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SituationId")
                        .HasDatabaseName("IX_AuditLogs_SituationId");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_AuditLogs_TimestampUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.ClarificationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("SituationVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Skippable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SituationVersionId")
                        .HasDatabaseName("IX_ClarificationQuestions_SituationVersionId");

                    b.ToTable("ClarificationQuestions");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTied")
                        .HasColumnType("bit");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<Guid>("SituationVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TiedNote")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SituationVersionId", "Rank")
                        .HasDatabaseName("IX_Issues_SituationVersionId_Rank");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.Situation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("OriginalSituationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Situations_ClientRequestId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Situations_CreatedAtUtc");

                    b.ToTable("Situations");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.SituationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawAiResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SituationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SituationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SituationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_SituationVersions_SituationId_VersionNumber");

                    b.ToTable("SituationVersions");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.ActionItem", b =>
                {
                    b.HasOne("NextStepWeb.Models.Entities.SituationVersion", "SituationVersion")
                        .WithMany("ActionItems")
                        .HasForeignKey("SituationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituationVersion");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.Assessment", b =>
                {
                    b.HasOne("NextStepWeb.Models.Entities.SituationVersion", "SituationVersion")
                        .WithOne("Assessment")
                        .HasForeignKey("NextStepWeb.Models.Entities.Assessment", "SituationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituationVersion");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("NextStepWeb.Models.Entities.Situation", "Situation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.ClarificationQuestion", b =>
                {
                    b.HasOne("NextStepWeb.Models.Entities.SituationVersion", "SituationVersion")
                        .WithMany("ClarificationQuestions")
                        .HasForeignKey("SituationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituationVersion");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.Issue", b =>
                {
                    b.HasOne("NextStepWeb.Models.Entities.SituationVersion", "SituationVersion")
                        .WithMany("Issues")
                        .HasForeignKey("SituationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituationVersion");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.SituationVersion", b =>
                {
                    b.HasOne("NextStepWeb.Models.Entities.Situation", "Situation")
                        .WithMany("Versions")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.Situation", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("NextStepWeb.Models.Entities.SituationVersion", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Assessment");

                    b.Navigation("ClarificationQuestions");

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
